spring.application.name=scms-backend

# Database Config - MongoDB
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://gondaleditz3519_db_user:R3ev8eTDPdf9T14B@cluster0.7lggwlw.mongodb.net/scms_db?appName=Cluster0}

# JWT Config
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
# Expiration: 24 hours in ms = 86400000
jwt.expiration=86400000

# Server Port
server.port=8081

